name: 04 - using actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Priniting Folders
          run: ls


        #0. Checkout the code from the repository
        #1. Install deps of our react app
        # 2. Execute automated tests