name: 08 - Using Variables

on:
    push:
    workflow_dispatch:
env:
    WORKFLOW_VAR: "I am a workflow env var"
    OVERWRITTEN: 'I will be overwritten'
    UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR ||  'default value'}}

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I am a job env var"
            OVERWRITTEN: 'I have been overwritten at job level'
        steps:
            - name: Print env variable
              env:
                  STEP_VAR: "I am a step env var"
                  STEP_VAR2: "I'm another step env var"
              run: |
                echo "Step env var: ${{ env.STEP_VAR }}"
                echo "Step env var2: ${{ env.STEP_VAR2 }}"
                echo "Job env var: ${{ env.JOB_VAR }}"
                echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
                echo "Overwritten env var: ${{ env.OVERWRITTEN }}"  

            - name: Overwritten job variable
              env:
                OVERWRITTEN: 'I have been overwritten at step level'
              run: |
                echo "Overwritten env var at step level: ${{ env.OVERWRITTEN }}"

    echo2:
        runs-on: ubuntu-latest
        steps:
            - name: Print Variables
              run: |
                  echo "Repo VAR: ${{ vars.REPOSITORY_VAR }}" 
    echo-prod:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Print Variables
              run: |
                  echo "Repo VAR: ${{ vars.TARGET_VAR }}" 
                  echo "Environment VAR: ${{ vars.TARGET_VAR }}" 
   echo-undefined:
        runs-on: ubuntu-latest
        steps:
            - name: Print Undefined Variables
              run: |
                  echo "Undefined VAR: ${{ env.UNDEFINED_VAR_WITH_DEFAULT }}" 
                  
            
